# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeManager < Formula
  desc ""
  homepage "https://github.com/RinkiyaKeDad/kube-manager"
  version "0.1"

  on_macos do
    url "https://github.com/RinkiyaKeDad/kube-manager/releases/download/v0.1/kube-manager_0.1_darwin_all.tar.gz"
    sha256 "ddc780f1ddc4aeee487d604915cad361a2fc1db41e6b52b1e6910b1254fe255e"

    def install
      bin.install "kube-manager"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RinkiyaKeDad/kube-manager/releases/download/v0.1/kube-manager_0.1_linux_arm64.tar.gz"
      sha256 "c5af086f467abfd0dca5faa266edc449c9e80b042d97552f6575dd9644870919"

      def install
        bin.install "kube-manager"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RinkiyaKeDad/kube-manager/releases/download/v0.1/kube-manager_0.1_linux_amd64.tar.gz"
      sha256 "721ea56a794194e297fe1c75e1c9d81b6518c14f58470120fb3a438c639e2afc"

      def install
        bin.install "kube-manager"
      end
    end
  end
end
